#!/usr/bin/env bash

#此模块检测是否存在某些监听
#入口: <port> [...]
#出口: 检测通过，输出yes

t=1

for i in "$@"; do
    ss -ntl | grep "$i"
    if [[ $? != 0 ]]; then
        t=0
        break
    fi
done

if [[ $t == 1 ]]; then echo yes; fi